# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Dieser Workflow wird ausgelöst, wenn du Code in den 'main'-Branch pushst

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Verwende einen Ubuntu-Server für den Build-Prozess

    steps:
      - name: Checkout deines Repositorys
        uses: actions/checkout@v3 # Holt deinen Code vom Repository

      - name: Node.js einrichten (für Bun)
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Wähle die Node.js-Version, die dein Projekt benötigt

      - name: Bun installieren
        uses: oven-sh/setup-bun@v1 # Eine spezielle Action, um Bun zu installieren
        with:
          bun-version: latest # Oder eine spezifische Version wie '1.0.0'

      - name: Abhängigkeiten installieren
        run: bun install # Installiert alle benötigten Pakete mit Bun

      - name: Projekt bauen
        run: bun run build # Führt den 'build'-Befehl aus deiner package.json aus, der den 'dist'-Ordner erstellt

      - name: Auf GitHub Pages deployen
        uses: peaceiris/actions-gh-pages@v3 # Eine beliebte Action zum Deployment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Dein GitHub-Token für die Authentifizierung
          publish_dir: ./dist # Der Ordner, der die gebauten Dateien enthält (der 'dist'-Ordner)
